version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
          time: "12:30"

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "12:30"
      ignore:
          - dependency-name: "@types/*"
